'use strict';
const assert = require('node:assert/strict');
const C = require('../compare-utils');
const Settings = require('../settings-utils');
const a = { t: [0, 1, 2, 3], v: [0, 2, 4, 6] };
const b = { t: [-2, 0, 1], v: [0, 4, 6] };
assert.equal(C.valueAt(a.t, a.v, -1), NaN);
assert.equal(C.valueAt(a.t, a.v, 0.5), 1);
assert.equal(C.valueAt(a.t, a.v, 0.5, true), 0);
assert.equal(C.valueAt([0, 1, 2], [1, NaN, 3], 0.5), NaN);
assert.equal(C.pointAt([[0, 1], [1, 3]], .5), 2);
assert.equal(C.pointAt([[0, 1], [1, 3]], .5, true), 1);
assert.equal(C.pointAt([[0, 1], [1, null]], .5), NaN);
assert.equal(C.pointAt([[0, 1], [1, 3]], 2), NaN);
assert.deepEqual(C.pointStats([[0, 1], [1, null], [2, 3], [3, Infinity]], 0, 3), { n: 2, min: 1, max: 3, mean: 2, rms: Math.sqrt(5), sigma: 1 });
let r = C.compare(a, b, 2, [0, 3], false, 1, true);
assert.equal(r.max, 0); assert.equal(r.n, 4); assert.equal(r.mean, 0); assert.equal(r.rms, 0);
assert.deepEqual(r.points, [[0, 0], [1, 0], [2, 0], [3, 0]]);
r = C.compare(a, { t: [0, 1, 2, 3], v: [0, 1, NaN, 2] }, 0, [1, 3], false, 2);
assert.equal(r.n, 2); assert.equal(r.missing, 1); assert.equal(r.max, 4); assert.equal(r.time, 3); assert.equal(r.mean, 2.5); assert.equal(r.exceeded, 1); assert.equal(r.ratio, 2);
r = C.compare(a, b, 100, [0, 3]); assert.equal(r.max, null); assert.equal(r.n, 0); assert.equal(r.missing, 4);
r = C.compare({ t: [0, 2, 4], v: [0, 1, 1] }, { t: [0, 1, 3, 4], v: [0, 1, 1, 1] }, 0, [0, 4], true);
assert.equal(r.mismatchDuration, 1); assert.equal(r.totalDuration, 4);
assert.equal(r.mainTransition.time, 2); assert.equal(r.subTransition.time, 1); assert.equal(r.transitionDelta, -1);
assert.equal(C.alignmentScore(a, b, 2, [0, 3]).rms, 0);
assert.equal(C.alignmentScore(a, b, 100, [0, 3]).rms, Infinity);
assert.equal(C.sameUnit(' km/h ', 'km/h'), true); assert.equal(C.sameUnit('m/s', 'km/h'), false);
const old = { _version: 5, selectedNames: ['車速'] }; const migrated = Settings.migrateSettings(old);
assert.equal(migrated.settings._version, 6); assert.deepEqual(migrated.settings.comparison, {}); assert.equal(old.comparison, undefined);
assert.equal(Settings.migrateSettings({ _version: 7 }).ok, false);
const cleaned = C.cleanSettings({ view: 'broken', labels: { 'ﾃｽﾄ.csv': '試験前' }, tolerances: { speed: -1, rpm: 2 }, notes: [{ text: 'bad', t0: 5, t1: 1 }], matches: { sub: { speed: '', rpm: 'Engine_RPM' } } });
assert.equal(cleaned.view, 'overlay'); assert.equal(cleaned.labels['ﾃｽﾄ.csv'], '試験前'); assert.deepEqual(cleaned.tolerances, { rpm: 2 }); assert.deepEqual(cleaned.notes, []); assert.equal(cleaned.matches.sub.speed, '');
const untrusted = C.cleanSettings(JSON.parse('{"labels":{"__proto__":"safe"},"matches":{"__proto__":{"x":"y"}}}'));
assert.equal({}.x, undefined); assert.equal(Object.getPrototypeOf(untrusted.labels), Object.prototype);
assert.equal(C.candidates({ name: 'Vehicle_Speed', unit: 'km/h' }, [{ name: 'Voltage', unit: 'V' }, { name: 'Vehicle Speed', unit: 'km/h' }])[0].col.name, 'Vehicle Speed');
console.log('compare-utils tests passed');
