'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
(async () => {
    const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
    const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, acceptDownloads: true });
    const page = await context.newPage(), errors = [];
    page.on('pageerror', e => errors.push(e.stack));
    const out = fs.mkdtempSync(path.join(os.tmpdir(), 'csv-比較-ﾃｽﾄ-'));
    const reference = ['Time,Pressure,State,Voltage', 's,kPa,,V'];
    const target = ['Time,Press_Actual,State,Voltage', 's,kPa,,mV'];
    for (let i = 0; i <= 200; i++) {
        const t = i / 10, v = Math.sin(t / 2) * 3 + t * 0.3;
        reference.push(`${t},${v},${t >= 10 ? 1 : 0},${2 + t}`);
        target.push(`${t + 2},${v},${t >= 10.5 ? 1 : 0},${(2 + t) * 1000}`);
    }
    fs.writeFileSync(path.join(out, '基準_ﾛｸﾞ.csv'), reference.join('\n'));
    fs.writeFileSync(path.join(out, '比較_ﾛｸﾞ.csv'), target.join('\n'));
    const state = fn => page.evaluate(fn);
    const select = async name => { await page.locator('#column-search').fill(name); const row = page.locator(`[data-channel="${name}"] .col-item-top`); await row.waitFor(); if (await row.getAttribute('aria-pressed') !== 'true') await row.click(); await page.locator('#column-search').fill(''); };
    const offset = () => state(() => Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'sub').offset);
    try {
        await page.goto(pathToFileURL(path.resolve(__dirname, '../index.html')).href);
        await page.locator('#file-input').setInputFiles([path.join(out, '基準_ﾛｸﾞ.csv'), path.join(out, '比較_ﾛｸﾞ.csv')]);
        await page.waitForFunction(() => Object.keys(window.__csvViewerDebug.state.files).length === 2 && window.__csvViewerDebug.state.parseJobs.size === 0);
        await select('Pressure'); await select('Voltage');
        await page.waitForFunction(() => document.querySelectorAll('[data-map-index]').length === 2);
        await page.locator('[data-map-index="0"]').selectOption('Press_Actual');
        await page.locator('#compare-map-apply').click();
        await page.waitForFunction(() => window.__csvViewerDebug.state.comparison.matches['比較_ﾛｸﾞ.csv']?.Pressure === 'Press_Actual');
        await page.locator('[data-pane="align"]').click(); await page.locator('#compare-align-channel').selectOption('Pressure');
        await page.locator('#compare-align-span').fill('5'); await page.locator('#compare-align-run').click();
        await page.waitForFunction(() => !document.getElementById('compare-align-apply').disabled);
        assert.equal(await offset(), 0);
        await page.locator('#compare-align-apply').click(); await page.waitForFunction(() => Math.abs(Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'sub').offset + 2) < 0.01);
        await page.locator('#undo-btn').click(); await page.waitForFunction(() => Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'sub').offset === 0);
        await page.locator('#redo-btn').click(); await page.waitForFunction(() => Math.abs(Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'sub').offset + 2) < 0.01);
        // Manual preview preserves applied state until explicitly accepted.
        await page.locator('.compare-manual > summary').click();
        await page.locator('#compare-anchor-main').fill('4'); await page.locator('#compare-anchor-sub').fill('5');
        await page.locator('#compare-align-manual').click();
        await page.waitForFunction(() => !document.getElementById('compare-align-apply').disabled);
        assert.ok(Math.abs(await offset() + 2) < .01);
        assert.ok((await page.locator('#compare-align-info').innerText()).includes('-1 s'));
        await page.locator('#compare-align-cancel').click(); assert.ok(Math.abs(await offset() + 2) < .01);
        // Pick corresponding points using the preview canvas itself.
        await page.locator('.compare-manual > summary').click(); await page.locator('#compare-align-pick').click();
        await page.waitForFunction(() => document.getElementById('compare-align-info').textContent.includes('実線'));
        const anchor = await state(() => { const el = document.getElementById('compare-align-preview'), chart = echarts.getInstanceByDom(el), rect = el.getBoundingClientRect(); return { x: rect.left + chart.convertToPixel({ xAxisIndex: 0 }, 4), y: rect.top + 100 }; });
        await page.mouse.click(anchor.x, anchor.y);
        await page.waitForFunction(() => document.getElementById('compare-align-info').textContent.includes('灰色'));
        await page.mouse.click(anchor.x, anchor.y);
        await page.waitForFunction(() => !document.getElementById('compare-align-apply').disabled);
        const pickedMain = Number(await page.locator('#compare-anchor-main').inputValue()), pickedSub = Number(await page.locator('#compare-anchor-sub').inputValue());
        assert.ok(Math.abs(pickedMain - 4) < .1 && Math.abs(pickedSub - pickedMain - 2) < .001);
        await page.locator('#compare-align-cancel').click();
        await page.locator('#compare-raw').check();
        assert.ok(Math.abs(await offset() + 2) < .01);
        const firstSubTime = await state(() => window.__csvViewerDebug.state.chart.getOption().series.find(s => s.name.includes('Press_Actual')).data[0][0]); assert.equal(firstSubTime, 2);
        await page.locator('#compare-raw').uncheck();
        await page.locator('[data-pane="results"]').click(); await page.locator('#compare-calculate').click();
        await page.waitForFunction(() => document.querySelectorAll('.compare-result').length === 2);
        assert.ok((await page.locator('#compare-results-list').innerText()).includes('単位不一致'));
        await page.locator('[data-view="diff"]').click();
        const diff = await state(() => window.__csvViewerDebug.state.chart.getOption().series.filter(s => s.id.startsWith('compare-diff')));
        assert.equal(diff.length, 1); assert.ok(diff[0].data.filter(p => p[1] !== null).every(p => Math.abs(p[1]) < 0.005));
        await page.locator('[data-view="overlay"]').click();
        const whole = await state(() => window.__csvViewerDebug.getVisibleXRange());
        await page.locator('#compare-overview-plot').click({ position: { x: 5, y: 20 } });
        const stillWhole = await state(() => window.__csvViewerDebug.getVisibleXRange()); assert.ok(Math.abs((whole[1] - whole[0]) - (stillWhole[1] - stillWhole[0])) < .01);
        await page.locator('#compare-alias-edit').click(); await page.locator('#compare-alias-channel').selectOption('Pressure'); await page.locator('#compare-alias-text').fill('圧力'); await page.locator('#compare-alias-save').click();
        await page.locator('#column-search').fill('圧力'); await page.waitForFunction(() => document.querySelectorAll('.col-item').length === 1);
        assert.equal(await page.locator('.col-item').getAttribute('data-channel'), 'Pressure'); await page.locator('#column-search').fill('');
        await select('State');
        await page.waitForFunction(() => window.__csvViewerDebug.state.gridRegions.some(r => r.name === 'State'));
        // Drag a channel onto the centre of another graph, then insert independently at an edge.
        const point = await state(() => { const d = window.__csvViewerDebug, r = d.state.gridRegions.find(r => r.name === 'State'), box = document.getElementById('chart').getBoundingClientRect(); return { x: 200, y: r.top + r.height / 2, absoluteX: box.x + 200, absoluteY: box.y + r.top + r.height / 2 }; });
        await page.locator('[data-channel="Pressure"]').dragTo(page.locator('#chart'), { targetPosition: { x: point.x, y: point.y } });
        await page.waitForFunction(() => window.__csvViewerDebug.state.chartGroups.some(g => g.channels.some(c => c.name === 'Pressure') && g.channels.some(c => c.name === 'State')));
        const insert = await state(() => { const r = window.__csvViewerDebug.state.gridRegions.find(r => r.label.includes('State')); return { x: 200, y: r.top + 12 }; });
        await page.locator('[data-channel="Pressure"]').dragTo(page.locator('#chart'), { targetPosition: insert });
        await page.waitForFunction(() => window.__csvViewerDebug.state.chartGroups.some(g => g.channels.length === 1 && g.channels[0].name === 'Pressure'));
        await page.locator('#compare-select-range').click();
        const points = await state(() => { const d = window.__csvViewerDebug, rect = document.getElementById('chart').getBoundingClientRect(), y = rect.top + d.state.gridRegions[0].top + 60; return { x0: rect.left + d.state.chart.convertToPixel({ xAxisIndex: 0 }, 4), x1: rect.left + d.state.chart.convertToPixel({ xAxisIndex: 0 }, 8), y }; });
        await page.mouse.move(points.x0, points.y); await page.mouse.down(); await page.mouse.move(points.x1, points.y, { steps: 12 }); await page.mouse.up();
        await page.locator('#compare-selection:not(.hidden)').waitFor();
        await page.waitForFunction(() => window.__csvViewerDebug.state.chart.getOption().series.some(s => s.id.startsWith('event-area-')));
        await page.locator('[data-range-action="note"]').click(); await page.locator('#compare-note-text').fill('圧力一致、状態だけ遅れ'); await page.locator('#compare-note-add').click();
        await page.waitForFunction(() => window.__csvViewerDebug.state.comparison.notes.length === 1);
        const note = await state(() => window.__csvViewerDebug.state.comparison.notes[0]); assert.ok(Math.abs(note.t0 - 4) < .2 && Math.abs(note.t1 - 8) < .2); assert.ok(note.image.startsWith('data:image/png'));
        await page.locator('#compare-template-name').fill('圧力と状態'); await page.locator('#compare-template-save').click();
        const downloadPromise = page.waitForEvent('download'); await page.locator('#compare-template-export').click(); const download = await downloadPromise; const templatePath = path.join(out, 'template.json'); await download.saveAs(templatePath);
        const template = JSON.parse(fs.readFileSync(templatePath, 'utf8')); assert.equal(template.settings.fileInfos, undefined); assert.equal(template.slots[0].align.offset, undefined); assert.deepEqual(template.settings.comparison.notes, []);
        await page.locator('#compare-template-select').selectOption('0'); await page.locator('#compare-template-apply').click();
        await page.waitForFunction(() => Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'sub').offset === 0);
        assert.equal(await state(() => window.__csvViewerDebug.state.comparison.matches['比較_ﾛｸﾞ.csv'].Pressure), 'Press_Actual');
        await page.locator('#compare-align-run').click(); await page.waitForFunction(() => !document.getElementById('compare-align-apply').disabled); await page.locator('#compare-align-cancel').click(); assert.equal(await offset(), 0);
        await page.locator('[data-pane="notes"]').click(); await page.locator('[data-note-jump]').click();
        await page.waitForFunction(() => Math.abs(Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'sub').offset + 2) < .01);
        await page.locator('#compare-template-import').setInputFiles(templatePath); await page.waitForFunction(() => Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'sub').offset === 0);
        await page.locator('[data-pane="prepare"]').click();
        const formerMain = await state(() => Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'main').name);
        const nextId = await state(() => Object.keys(window.__csvViewerDebug.state.files).find(id => window.__csvViewerDebug.state.files[id].role === 'sub'));
        await page.locator('#compare-main').selectOption(nextId);
        await page.waitForFunction(old => Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'main').name !== old, formerMain);
        await page.locator('[data-pane="notes"]').click(); await page.locator('[data-note-jump]').click();
        await page.waitForFunction(old => Object.values(window.__csvViewerDebug.state.files).find(f => f.role === 'main').name === old, formerMain);
        await page.setViewportSize({ width: 900, height: 700 }); await page.locator('#compare-panel-toggle').click(); assert.equal(await page.locator('#compare-panel').isVisible(), false);
        assert.equal(await state(() => document.documentElement.scrollWidth <= window.innerWidth), true);
        assert.deepEqual(errors, []);
        console.log('Comparison interactions passed:', out);
    } catch (e) { console.error('Panel:', await page.locator('#compare-panel-content').innerText()); console.error('Errors:', errors); console.error('Artifacts:', out); await page.screenshot({ path: path.join(out, 'failure.png') }); throw e; }
    finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
